### ISSUE TITLE
Please help to list the steps to get this up and running

### ISSUE THREAD

**Issue by leomayleomay** [wokalski/otodom-scraper#1]
I tried to build it with `esy install & esy build`, got error saying

```
09:24 $ esy install
info esy install 0.2.6
warn found esyi.lock.json, please rename it to esy.lock.json
esyi: corrupted esyi.lock.json lockfile
      you might want to remove it and install from scratch
      error: Solution.LockfileV1.t


esy: error, exiting...
     error running command:
     '/Users/hao/.nvm/versions/node/v6.9.2/lib/node_modules/esy/_build/default/esyi/bin/esyi.exe'
```

not sure what I have missed, please help to list the steps, cheers

**Comment by wokalski** [comment]
It's probably an old version of the lock file in respect to the esy version you're using. Just remove the lock file 😄.

Why are you using this project btw?

**Comment by leomayleomay** [comment]
Cheers, after removing the lock file, it does work, :), I am trying to learn how to write a scraper with OCaml/ReasonML and this repo seems to be a really good example, thank you for the work

**Comment by wokalski** [comment]
@leomayleomay feel free to submit a PR with an updated lock file.
